=== uku3lig/uklient-java/src/main/resources/mod.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "mod",
  "title": "Mod",
  "description": "Mod",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "provider": {
        "enum": [
          "modrinth",
          "curseforge"
        ]
      },
      "dependencies": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "fallback": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "minecraftVersion": {
              "type": "string",
              "pattern": "^1(\\.\\d{1,2}){1,2}$"
            },
            "versionId": {
              "type": "string"
            }
          },
          "required": [
            "minecraftVersion",
            "versionId"
          ]
        }
      },
      "config": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "id",
      "provider",
      "fallback"
    ]
  }
}

=== uku3lig/uklient-java/src/main/resources/mods.json
[
  {
    "name": "sodium",
    "id": "AANobbMI",
    "provider": "modrinth",
    "fallback": [
      {
        "minecraftVersion": "1.17.1",
        "versionId": "6YGRDUVT"
      },
      {
        "minecraftVersion": "1.18",
        "versionId": "3JJvf9Kn"
      }
    ],
    "dependencies": [
      "AZomiSrC",
      "hEOCdOgW"
    ],
    "config": "sodiumDir"
  },
  {
    "name": "litematica",
    "id": "308892",
    "provider": "curseforge",
    "fallback": [],
    "dependencies": [
      "303119",
      "244260"
    ]
  }
]
